default_mission_planner_bt_xml: auv3/bin_mission_cover_pool.xml
plugin_lib_names:
  - mp_navigate_to_pose_bt_node
  - mp_navigate_control_bt_node
  - mp_move_forward_demo_bt_node
  - mp_update_pose_bt_node
  - mp_is_distance_traveled_condition_bt_node
  - mp_is_time_expired_condition_bt_node
  - mp_convert_odom_to_pose_bt_node
  - mp_find_buoy_bt_node
  - mp_update_detected_objects_bt_node
  - mp_set_relative_goal_bt_node
  - mp_controller_service_bt_node
  - mp_detector_auv_service_bt_node
  - mp_adder_bt_node
  - mp_calc_pic_angle_bt_node
  - mp_choose_pic_bt_node
  - mp_set_adjustment_bt_node
  - mp_is_lid_seen_condition_bt_node
  - mp_is_pic_centered_condition_bt_node
  - mp_is_enough_pic_seen_condition_bt_node
  - mp_manipulators_service_bt_node
  - mp_is_center_aligned_condition_bt_node
  - mp_is_handle_flat_condition_bt_node
  - mp_calc_cover_setpoint_bt_node
  - mp_is_part_bin_seen_condition_bt_node
  - mp_is_cover_flat_condition_bt_node
  - mp_is_full_bin_seen_condition_bt_node

odom_topic: /auv3/nav/odom_ned
transform_tolerance: 0.1

bt_loop_duration: 10
default_server_timeout: 20
enable_groot_monitoring: false
groot_zmq_publisher_port: 1666
groot_zmq_server_port: 1667 
