default_mission_planner_bt_xml: robosub21_auv4.xml
plugin_lib_names:
  - mp_navigate_to_pose_bt_node
  - mp_move_forward_demo_bt_node
  - mp_update_pose_bt_node
  - mp_is_distance_traveled_condition_bt_node
  - mp_convert_odom_to_pose_bt_node
odom_topic: /auv4/nav/odom_ned
transform_tolerance: 0.1

bt_loop_duration: 10
default_server_timeout: 20
enable_groot_monitoring: false
groot_zmq_publisher_port: 1666
groot_zmq_server_port: 1667 
