default_mission_planner_bt_xml: auv3/robosub21.xml
plugin_lib_names:
  - mp_navigate_to_pose_bt_node
  - mp_set_relative_goal_bt_node
  - mp_update_pose_bt_node
  - mp_is_distance_traveled_condition_bt_node
  - mp_is_time_expired_condition_bt_node
  - mp_convert_odom_to_pose_bt_node
  - mp_controller_service_bt_node
  - mp_detector_auv_service_bt_node
  - mp_get_yaw_between_poses_bt_node
  - mp_split_pose_components_bt_node
  - mp_dynamic_timeout_sequence_bt_node
  - mp_dynamic_timeout_bt_node
  - mp_get_distance_between_poses_bt_node
  - mp_update_detected_objects_bt_node
  - mp_set_object_goal_bt_node

odom_topic: /auv3/nav/odom_ned
transform_tolerance: 0.1

bt_loop_duration: 10
default_server_timeout: 20
enable_groot_monitoring: false
groot_zmq_publisher_port: 1666
groot_zmq_server_port: 1667 
